name: EMS
channels:
  - conda-forge
  - defaults
dependencies:
  - blas[build=mkl]
  - python=3.10
  - pandas
  - cvxpy
  - google-auth
  - dask
  - coiled
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git
