channels:
  - conda-forge
  - defaults
dependencies:
  - blas[build=mkl]
  - python=3.10
  - pandas
  - cvxpy
  - google-auth
  - pandas-gbq>=0.19.2
  - dask
  - coiled
  - sqlalchemy
  - pg8000
  - cloud-sql-python-connector
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git
