name: EMS
channels:
  - conda-forge
  - defaults
dependencies:
  - blas[build=mkl]
  - python=3.10
  - pandas
  - google-auth
  - pandas-gbq
  - dask
  - coiled
  - sqlalchemy
  - pg8000
  - cloud-sql-python-connector
  - pip
  - pip:
    - git+https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/adonoho/EMS.git
