name: EMS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scipy
  - cvxpy
  - pandas-gbq
  - dask
  - blas[build=mkl]
  - sqlalchemy
  - pg8000
  - cloud-sql-python-connector
  - pip
  - pip:
    - dask-saturn>=0.3.0
